# Generated by Django 5.1.4 on 2025-03-01 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_default_shipping_address'),
        ('users', '0004_otp'),
    ]

    operations = [
    ]
