# Generated by Django 5.1.4 on 2025-04-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_adminnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotification',
            name='event_type',
            field=models.CharField(default='rose villa house kochi', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='adminnotification',
            table='users_adminnotification',
        ),
    ]
