# Generated by Django 5.1.4 on 2026-01-24 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_deleteaccountotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorAccount',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_account_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('razorpay_linked_account_status', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_account_holder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_status', models.CharField(choices=[('pending', 'Pending Verification'), ('active', 'Active'), ('suspended', 'Suspended'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('kyc_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vendor_accounts',
            },
        ),
        migrations.CreateModel(
            name='KYCVerification',
            fields=[
                ('kyc_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('aadhaar', 'Aadhaar Card'), ('pan', 'PAN Card'), ('bank_statement', 'Bank Statement'), ('business_proof', 'Business Proof'), ('gst_certificate', 'GST Certificate')], max_length=50)),
                ('document_number', models.CharField(blank=True, max_length=100, null=True)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='kyc_documents/')),
                ('quickekyc_verification_id', models.CharField(blank=True, max_length=255, null=True)),
                ('quickekyc_response', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('resubmit', 'Resubmit Required')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_kyc_documents', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to='users.vendoraccount')),
            ],
            options={
                'db_table': 'kyc_verifications',
                'unique_together': {('vendor', 'document_type')},
            },
        ),
    ]
