# Generated by Django 5.1.4 on 2026-01-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_vendoraccount_kycverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('staff', 'Staff'), ('owner', 'Owner')], default='customer', max_length=10),
        ),
    ]
