# Generated by Django 5.1.4 on 2026-01-24 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderdetail_price_at_purchase'),
        ('users', '0009_vendoraccount_kycverification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='current_location_lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='current_location_lng',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_transfer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='settlement_status',
            field=models.CharField(choices=[('pending', 'Pending Settlement'), ('initiated', 'Settlement Initiated'), ('completed', 'Settlement Completed'), ('failed', 'Settlement Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='users.vendoraccount'),
        ),
        migrations.AddField(
            model_name='order',
            name='vendor_settlement_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='DeliveryPartner',
            fields=[
                ('partner_id', models.AutoField(primary_key=True, serialize=False)),
                ('partner_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('vehicle_type', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=20, null=True)),
                ('current_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('current_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_delivery', 'On Delivery'), ('offline', 'Offline'), ('suspended', 'Suspended')], default='available', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_deliveries', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_partner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'delivery_partners',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.deliverypartner'),
        ),
        migrations.CreateModel(
            name='OrderLocationHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('status_at_location', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.deliverypartner')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='orders.order')),
            ],
            options={
                'db_table': 'order_location_history',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentSettlement',
            fields=[
                ('settlement_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('settlement_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('razorpay_transfer_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('razorpay_transfer_response', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='orders.order')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='users.vendoraccount')),
            ],
            options={
                'db_table': 'payment_settlements',
                'ordering': ['-initiated_at'],
            },
        ),
    ]
