# Generated by Django 5.1.4 on 2025-03-18 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_category_code_product_discount_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='offer_price',
        ),
    ]
